export const techProducts = [
  // Laptops
  {
    category: "Laptops",
    id: 1,
    name: "Laptop Pro 14",
    description: "High-performance laptop with 14-inch Retina display.",
    model: "LP14-PRO",
    brand: "CHAPPLE",
    price: 150000,
    salePrice: 140000,
    buyLink: "https://example.com/laptop-pro-14",
    imgSrc:
      "https://ipowerresale.com/cdn/shop/files/media_80920579-9a67-4b08-af0c-570e9099bf74.png",
  },
  {
    category: "Laptops",
    id: 2,
    name: "Laptop Air 13",
    description: "Lightweight laptop with ultra-slim design.",
    model: "LA13-AIR",
    brand: "PELL",
    price: 100000,
    salePrice: 90999,
    buyLink: "https://example.com/laptop-air-13",
    imgSrc:
      "https://gmae.pk/wp-content/uploads/2024/02/GMAE-Product-Apple-MacBook-Air-13-inch-MGN63-M1-0.webp",
  },
  {
    category: "Laptops",
    id: 3,
    name: "Gaming Laptop Z",
    description: "High-performance gaming laptop with RTX graphics.",
    model: "GL-Z",
    brand: "GameTech",
    price: 200000,
    salePrice: 190000,
    buyLink: "https://example.com/gaming-laptop-z",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL1GvDUzLif5T7pK_VuB-y6gm52Y_EzLiBCg&s",
  },
  {
    category: "Laptops",
    id: 4,
    name: "Ultrabook X1",
    description: "Sleek and powerful ultrabook for professionals.",
    model: "UX1",
    brand: "PH",
    price: 180000,
    salePrice: 170000,
    buyLink: "https://example.com/ultrabook-x1",
    imgSrc:
      "https://p3-ofp.static.pub//fes/cms/2024/07/05/05dhzg0lrtq4i0d3wxqyjjakwmbmzr331426.png",
  },
  {
    category: "Laptops",
    id: 5,
    name: "Budget Laptop B10",
    description: "Affordable laptop for everyday use.",
    model: "BL10",
    brand: "PH",
    price: 70000,
    salePrice: 65000,
    buyLink: "https://example.com/budget-laptop-b10",
    imgSrc:
      "https://image.made-in-china.com/2f0j00ZbMhfaDCYsUR/2023-Hot-Selling-Buy-Cheap-Laptops-in-China-14-1-Inch-12GB-16GB-RAM-512-SSD-High-Quality-Gaming-Office-Computer-Laptop.webp",
  },
  {
    category: "Laptops",
    id: 6,
    name: "2-in-1 Convertible Laptop",
    description: "Convertible laptop with touchscreen functionality.",
    model: "2IN1-15",
    brand: "PELL",
    price: 130000,
    salePrice: 125000,
    buyLink: "https://example.com/2-in-1-convertible",
    imgSrc:
      "https://image.made-in-china.com/2f0j00EMablJcyrfod/2-in-1-Laptop-Computer-Tablet-PC-14-Inch-Ultra-Slim-Notebook-RAM-12GB.webp",
  },
  {
    category: "Laptops",
    id: 7,
    name: "Laptop M15",
    description: "15-inch laptop with extended battery life.",
    model: "M15",
    brand: "PELL",
    price: 110000,
    salePrice: 105000,
    buyLink: "https://example.com/laptop-m15",
    imgSrc:
      "https://image.made-in-china.com/43f34j00zPTkcJoIJfqG/OEM-15-6-Inch-Intel-Core-3700u-Laptop-Computer-for-Studying-Business.jpg",
  },
  {
    category: "Laptops",
    id: 8,
    name: "Creator Laptop C17",
    description: "Powerful laptop for content creators.",
    model: "CL-C17",
    brand: "EduTech",
    price: 220000,
    salePrice: 210000,
    buyLink: "https://example.com/creator-laptop-c17",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hxbDgEamZmt92hvigrtsHvWqbz3RO2c3Ag&s",
  },
  {
    category: "Laptops",
    id: 9,
    name: "Business Laptop BL",
    description: "Durable and secure laptop for business needs.",
    model: "BL-PRO",
    brand: "EduTech",
    price: 170000,
    salePrice: 165000,
    buyLink: "https://example.com/business-laptop-bl",
    imgSrc:
      "https://image.made-in-china.com/318f0j00iTfRIeQEoVkY/6%E6%9C%8821%E6%97%A5%283%29.mp4.webp",
  },
  {
    category: "Laptops",
    id: 10,
    name: "Student Laptop S14",
    description: "Affordable laptop designed for students.",
    model: "SL14",
    brand: "EduTech",
    price: 80000,
    salePrice: 75000,
    buyLink: "https://example.com/student-laptop-s14",
    imgSrc:
      "https://image.made-in-china.com/2f0j00NoFqOsVytPbm/2023-Wholesale-Shenzhen-China-Student-Used-Laptops-14-Inch-Laptops-OEM-Intel-Core-I5-I7-Laptop-Business-Gaming-Laptop-Notebook-Computer-Intel-Core-I7-Laptop.jpg",
  },

  // Monitors
  {
    category: "Monitors",
    id: 41,
    name: "24-inch LED Monitor",
    description: "Full HD LED monitor with vibrant display.",
    model: "LED24HD",
    brand: "ViewTech",
    price: 20000,
    salePrice: 19999,
    buyLink: "https://example.com/24-inch-led-monitor",
    imgSrc:
      "https://image.made-in-china.com/2f0j00hcvkimSzkjbY/18-5-19-20-21-5-22-23-24-27-Inch-LED-LCD-Gaming-Computer-Monitor.webp",
  },
  {
    category: "Monitors",
    id: 42,
    name: "32-inch Curved Monitor",
    description: "Immersive curved monitor with ultra-wide view.",
    model: "CURVE32",
    brand: "ScreenPro",
    price: 40000,
    salePrice: 33999,
    buyLink: "https://example.com/32-inch-curved-monitor",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0tE0co6Bx369WUm_9R4Cl-OkM172HEo6i0w&s",
  },
  {
    category: "Monitors",
    id: 43,
    name: "Gaming Monitor 27-inch",
    description: "High refresh rate gaming monitor for smooth gameplay.",
    model: "GM27",
    brand: "GameTech",
    price: 40000,
    salePrice: 38000,
    buyLink: "https://example.com/gaming-monitor-27-inch",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdHO8dLwFiTwVqVa_PsVEusUXRt_fFCy06Vw&s",
  },
  {
    category: "Monitors",
    id: 44,
    name: "4K UHD Monitor 28-inch",
    description: "Stunning 4K resolution for professional tasks.",
    model: "4KUHD28",
    brand: "UltraView",
    price: 50000,
    salePrice: 37000,
    buyLink: "https://example.com/4k-uhd-monitor-28-inch",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyzNG08Ng5VxIOGmOrXoCvJwUdT0SaLcP99g&s",
  },
  {
    category: "Monitors",
    id: 45,
    name: "Portable Monitor 15.6-inch",
    description: "Lightweight and portable monitor for on-the-go work.",
    model: "PORT156",
    brand: "TravelScreen",
    price: 25000,
    salePrice: 22000,
    buyLink: "https://example.com/portable-monitor-15.6-inch",
    imgSrc:
      "https://image.made-in-china.com/2f0j00cOToYhQKhNkR/New-OEM-ODM-13-3-15-6-16-17-3-Inch-USB-C-Monitor-Portable-Built-in-Battery-10000mAh-Touch-Screen-4K-Portable-Monitor-for-Laptop.webp",
  },
  {
    category: "Monitors",
    id: 46,
    name: "OLED Monitor 27-inch",
    description: "High-performance OLED monitor with vivid colors.",
    model: "OLED27",
    brand: "DisplayTech",
    price: 60000,
    salePrice: 54000,
    buyLink: "https://example.com/oled-monitor-27-inch",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZJGTXtegYuVD71IVqE7rZZF4GqoZv8ivIfw&s",
  },
  {
    category: "Monitors",
    id: 47,
    name: "Dual Monitor Setup",
    description: "Pair of monitors for multitasking efficiency.",
    model: "DUALMON",
    brand: "WorkPro",
    price: 45000,
    salePrice: 42000,
    buyLink: "https://example.com/dual-monitor-setup",
    imgSrc:
      "https://s.alicdn.com/@sc04/kf/H9eedd563bcb043948a9e7460da6ba6f9Q.jpg_300x300.jpg",
  },
  {
    category: "Monitors",
    id: 48,
    name: "34-inch UltraWide Monitor",
    description: "Ultra-wide screen for immersive viewing experience.",
    model: "UW34",
    brand: "WideView",
    price: 70000,
    salePrice: 67000,
    buyLink: "https://example.com/ultrawide-monitor-34-inch",
    imgSrc:
      "https://image.made-in-china.com/202f0j00UToGlYmPFQgp/34-Inch-21-9-Flat-Ultra-Wide-Screen-LED-Gaming-Monitor.webp",
  },
  {
    category: "Monitors",
    id: 49,
    name: "Touchscreen Monitor 22-inch",
    description: "Interactive touchscreen display for versatile use.",
    model: "TOUCH22",
    brand: "TouchTech",
    price: 30000,
    salePrice: 22000,
    buyLink: "https://example.com/touchscreen-monitor-22-inch",
    imgSrc:
      "https://s.alicdn.com/@sc04/kf/Heeda417362ce423f89eb4d806102b201g.jpg_300x300.jpg",
  },
  {
    category: "Monitors",
    id: 50,
    name: "5K Retina Monitor 27-inch",
    description: "Crystal-clear 5K resolution monitor for creators.",
    model: "5KRET27",
    brand: "VisionPro",
    price: 120000,
    salePrice: 115000,
    buyLink: "https://example.com/5k-retina-monitor-27-inch",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_zzU_7iytkgXmwaK_SaXvnNT4IfPQcDLw1g&s",
  },

  // Keyboards
  {
    category: "Keyboards",
    id: 11,
    name: "Mechanical Keyboard RGB",
    description: "Premium mechanical keyboard with RGB lighting.",
    model: "MK-RGB",
    brand: "KeyboardCo",
    price: 120000,
    salePrice: 100000,
    buyLink: "https://example.com/mechanical-keyboard-rgb",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRITZnDalZ4uf3BAsh0YLzvlMGFt7l5SWXLeQ&s",
  },
  {
    category: "Keyboards",
    id: 12,
    name: "Wireless Keyboard Slim",
    description: "Compact wireless keyboard for minimal setups.",
    model: "WK-SLIM",
    brand: "KeyboardCo",
    price: 1800,
    salePrice: 699,
    buyLink: "https://example.com/wireless-keyboard-slim",
    imgSrc:
      "https://image.made-in-china.com/318f0j00ETQGcbRaBWzO/1%E6%9C%8810%E6%97%A5+%281%29.mp4.webp",
  },
  {
    category: "Keyboards",
    id: 13,
    name: "Gaming Keyboard GX",
    description: "High-speed gaming keyboard with macro keys.",
    model: "GK-GX",
    brand: "GamerGear",
    price: 15000,
    salePrice: 10000,
    buyLink: "https://example.com/gaming-keyboard-gx",
    imgSrc:
      "https://image.made-in-china.com/43f34j00lceqjhFJpukZ/USB-Plug-Cable-Gaming-Office-Typing-Universal-Computer-Keyboard-and-Mouse.jpg",
  },
  {
    category: "Keyboards",
    id: 14,
    name: "Ergonomic Keyboard Pro",
    description: "Ergonomic design for comfortable typing.",
    model: "EK-PRO",
    brand: "ComfortKeys",
    price: 4000,
    salePrice: 2599,
    buyLink: "https://example.com/ergonomic-keyboard-pro",
    imgSrc:
      "https://i5.walmartimages.com/asr/72c8bed4-6fb3-468d-9879-9f4c9ec5a995.2bf859d759f28557874e5bde48fe2541.jpeg",
  },
  {
    category: "Keyboards",
    id: 15,
    name: "Backlit Keyboard 101",
    description: "Stylish keyboard with adjustable backlight.",
    model: "BK-101",
    brand: "BrightKeys",
    price: 4000,
    salePrice: 3200,
    buyLink: "https://example.com/backlit-keyboard-101",
    imgSrc:
      "https://m.media-amazon.com/images/I/61Z7j6w-zSL._AC_UF100000,1000_QL80_.jpg",
  },
  {
    category: "Keyboards",
    id: 16,
    name: "Mechanical Keyboard Blue",
    description: "Tactile and clicky mechanical keyboard.",
    model: "MK-BLUE",
    brand: "KeyboardCo",
    price: 11000,
    salePrice: 7000,
    buyLink: "https://example.com/mechanical-keyboard-blue",
    imgSrc:
      "https://image.made-in-china.com/2f0j00nzQkpVwKnAra/Chinese-Mechanical-Keyboard-Dazzling-Light-Effect-Infrared-Axis-Esports-Game.webp",
  },
  {
    category: "Keyboards",
    id: 17,
    name: "Bluetooth Keyboard BK1",
    description: "Portable Bluetooth keyboard for multiple devices.",
    model: "BTK-BK1",
    brand: "ConnectTech",
    price: 3000,
    salePrice: 1300,
    buyLink: "https://example.com/bluetooth-keyboard-bk1",
    imgSrc:
      "https://img.drz.lazcdn.com/static/pk/p/c793b6da26cc800c5109b414680338a2.jpg_720x720q80.jpg",
  },
  {
    category: "Keyboards",
    id: 18,
    name: "Compact Keyboard Mini",
    description: "Ultra-compact keyboard for tight spaces.",
    model: "CK-MINI",
    brand: "KeySlim",
    price: 6000,
    salePrice: 4000,
    buyLink: "https://example.com/compact-keyboard-mini",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1VdLtesC_PnICw9PY8A7muN6S85-RG7Z1IUaJkoomEfsIJnVkwqt9MU_ncgf6ddfSSx4&usqp=CAU",
  },
  {
    category: "Keyboards",
    id: 19,
    name: "Gaming Keyboard RGBX",
    description: "Advanced RGB gaming keyboard with programmable keys.",
    model: "GK-RGBX",
    brand: "GamerGear",
    price: 2300,
    salePrice: 2000,
    buyLink: "https://example.com/gaming-keyboard-rgbx",
    imgSrc:
      "https://www.yohohongkong.com/_next/image?url=https%3A%2F%2Fwww1.yohohongkong.com%2Fimages%2F202102%2Fgoods_img%2F45588_P_1613096754975.png&w=960&q=100",
  },
  {
    category: "Keyboards",
    id: 20,
    name: "Office Keyboard White",
    description: "Simple and durable keyboard for office use.",
    model: "OK-WHITE",
    brand: "OfficeTech",
    price: 2000,
    salePrice: 1500,
    buyLink: "https://example.com/office-keyboard-white",
    imgSrc:
      "https://image.made-in-china.com/318f0j00maJUSgckZHRq/%E8%A7%86%E9%A2%91.mp4.webp",
  },

  // Games DVDs
  {
    category: "Games",
    id: 21,
    name: "Game DVD: Action Heroes",
    description: "An action-packed game with immersive gameplay.",
    model: "GD-AH",
    brand: "GameWorld",
    price: 3000,
    salePrice: 1499,
    buyLink: "https://example.com/game-dvd-action-heroes",
    imgSrc:
      "https://i5.walmartimages.com/seo/Bruce-Willis-Action-Hero-Collection-4-DVD-Set-Precious-Cargo-The-Prince-Setup-Vice-Steelbook-Edition-NON-USA-FORMAT-PAL-Reg-2-Import-Denmark_fb1ccf7e-8c7d-4820-84cd-9ae3323da113.1aaffaf471f6552c80630c1f3d6b7144.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
  },
  {
    category: "Games",
    id: 22,
    name: "Game DVD: Speed Racer",
    description: "High-speed racing game with stunning graphics.",
    model: "GD-SR",
    brand: "RacePro",
    price: 1100,
    salePrice: 799,
    buyLink: "https://example.com/game-dvd-speed-racer",
    imgSrc:
      "https://assets-prd.ignimgs.com/2022/04/20/speedracertvg-1650489219936.jpg",
  },
  {
    category: "Games",
    id: 23,
    name: "Game DVD: Battle Royale",
    description: "Multiplayer battle royale with exciting challenges.",
    model: "GD-BR",
    brand: "GameWorld",
    price: 699,
    salePrice: 399,
    buyLink: "https://example.com/game-dvd-battle-royale",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxA2_2FtO99tF3Fve6vSPUERjPz4jp5p2Xiw&s",
  },
  {
    category: "Games",
    id: 24,
    name: "Game DVD: Galactic Wars",
    description: "Sci-fi game set in an expansive galaxy.",
    model: "GD-GW",
    brand: "SpaceGame",
    price: 1100,
    salePrice: 750,
    buyLink: "https://example.com/game-dvd-galactic-wars",
    imgSrc:
      "https://cdna.artstation.com/p/assets/images/images/047/085/218/large/alexander-tanasie-ef-dvd-case-b-1-1.jpg?1646731396",
  },
  {
    category: "Games",
    id: 25,
    name: "Game DVD: Fantasy Quest",
    description: "A magical adventure game full of quests.",
    model: "GD-FQ",
    brand: "QuestMaster",
    price: 1100,
    salePrice: 799,
    buyLink: "https://example.com/game-dvd-fantasy-quest",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkBwnrs5BX9Ysi2H64fN2einGdA-ieGxmt1A&s",
  },
  {
    category: "Games",
    id: 26,
    name: "Game DVD: Zombie Apocalypse",
    description: "Survive the zombie outbreak in this thrilling game.",
    model: "GD-ZA",
    brand: "GameWorld",
    price: 5000,
    salePrice: 4499,
    buyLink: "https://example.com/game-dvd-zombie-apocalypse",
    imgSrc: "https://i.ebayimg.com/images/g/KzsAAOSw3thj5vhL/s-l400.jpg",
  },
  {
    category: "Games",
    id: 27,
    name: "Game DVD: Ninja Warriors",
    description: "Stealth action game with challenging missions.",
    model: "GD-NW",
    brand: "ActionGear",
    price: 1300,
    salePrice: 799,
    buyLink: "https://example.com/game-dvd-ninja-warriors",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjt9H6ixBsP6FmXe8Mjv0RRwtCBeuKmX_Z0g&s",
  },
  {
    category: "Games",
    id: 28,
    name: "Game DVD: Alien Invasion",
    description: "Defend Earth against alien invaders.",
    model: "GD-AI",
    brand: "SpaceGame",
    price: 1200,
    salePrice: 750,
    buyLink: "https://example.com/game-dvd-alien-invasion",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpUfBxG8qmXunsJJMjHDWE_W9Yv_SMJMZbAg&s",
  },
  {
    category: "Games",
    id: 29,
    name: "Game DVD: Medieval Battle",
    description: "Experience epic medieval battles.",
    model: "GD-MB",
    brand: "BattleTech",
    price: 1000,
    salePrice: 799,
    buyLink: "https://example.com/game-dvd-medieval-battle",
    imgSrc:
      "https://m.media-amazon.com/images/I/51yRzAvLDrL._AC_UF894,1000_QL80_.jpg",
  },
  {
    category: "Games",
    id: 30,
    name: "Game DVD: Space Explorers",
    description: "Explore new worlds in this exciting space game.",
    model: "GD-SE",
    brand: "QuestMaster",
    price: 899,
    salePrice: 500,
    buyLink: "https://example.com/game-dvd-space-explorers",
    imgSrc:
      "https://spielefaible.de/files/images/spaceexplorers/SPACE_EXPLORERS_Packshot-web.png",
  },

  // Other DVDs (for Windows)
  {
    category: "DVDs",
    id: 31,
    name: "MS Office 2023",
    description: "Latest version of Microsoft Office suite.",
    model: "DVD-MS23",
    brand: "Microsoft",
    price: 15000,
    salePrice: 10000,
    buyLink: "https://example.com/ms-office-2023",
    imgSrc:
      "https://cdn.dsmcdn.com/mnresize/400/-/ty991/product/media/images/prod/SPM/PIM/20230826/00/67b03ddc-7442-31a2-a515-11e0fcdd8460/1_org.jpg",
  },
  {
    category: "DVDs",
    id: 32,
    name: "Windows 11 Pro",
    description: "Professional edition of Windows 11.",
    model: "DVD-W11P",
    brand: "Microsoft",
    price: 12000,
    salePrice: 4000,
    buyLink: "https://example.com/windows-11-pro",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiw2US98XnKthA7xiE1Oi2FNe2D2w9QvbUI5VJY4dTq6wKpzRsMH5yq1wuhYReihfO8X8&usqp=CAU",
  },
  {
    category: "DVDs",
    id: 33,
    name: "Antivirus Pro 2024",
    description: "Advanced antivirus protection for your PC.",
    model: "DVD-AV24",
    brand: "SecureSoft",
    price: 5000,
    salePrice: 3499,
    buyLink: "https://example.com/antivirus-pro-2024",
    imgSrc:
      "https://buyantiviruskey.in/wp-content/uploads/2024/05/Quick-heal-antivirus-pro-1.webp",
  },
  {
    category: "DVDs",
    id: 34,
    name: "Photo Editor Pro",
    description: "Professional photo editing software.",
    model: "DVD-PEP",
    brand: "EditMaster",
    price: 1599,
    salePrice: 999,
    buyLink: "https://example.com/photo-editor-pro",
    imgSrc:
      "https://play-lh.googleusercontent.com/UJomRoG1XBqfdUpf-FXJtaGlqxEnDiv7FIYZ8gahG74qgj1kPjvR1WNmMR0Fq53s8X8",
  },
  {
    category: "DVDs",
    id: 35,
    name: "Video Maker Suite",
    description: "Comprehensive tools for video creation.",
    model: "DVD-VMS",
    brand: "CreateSoft",
    price: 1000,
    salePrice: 499,
    buyLink: "https://example.com/video-maker-suite",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDLWm_j6HGfvzV36ZVe2U7bzKXkZfaVJecUA&s",
  },
  {
    category: "DVDs",
    id: 36,
    name: "Data Recovery Tool",
    description: "Recover lost data with this efficient software.",
    model: "DVD-DRT",
    brand: "RecoverSoft",
    price: 700,
    salePrice: 350,
    buyLink: "https://example.com/data-recovery-tool",
    imgSrc:
      "https://i0.wp.com/thelocalne.ws/wp-content/uploads/2023/01/laptop-hard-drive-data.jpg?fit=771%2C406&ssl=1",
  },
  {
    category: "DVDs",
    id: 37,
    name: "Audio Editor Suite",
    description: "Edit and mix audio like a pro.",
    model: "DVD-AES",
    brand: "SoundSoft",
    price: 350,
    salePrice: 99,
    buyLink: "https://example.com/audio-editor-suite",
    imgSrc:
      "https://cdn.dribbble.com/userupload/10503959/file/original-4670cac596b3586fc2b99cb8b7351577.png?resize=752x&vertical=center",
  },
  {
    category: "DVDs",
    id: 38,
    name: "Programming IDE Pro",
    description: "Integrated development environment for coding.",
    model: "DVD-IDEP",
    brand: "CodeMaster",
    price: 999,
    salePrice: 499,
    buyLink: "https://example.com/programming-ide-pro",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROtxG1F-Ut9VPO5-vyxodf3V0unk5KOX2MmA&s",
  },
  {
    category: "DVDs",
    id: 39,
    name: "Database Manager 2024",
    description: "Tool for managing and analyzing databases.",
    model: "DVD-DBM24",
    brand: "DataSoft",
    price: 499,
    salePrice: 199,
    buyLink: "https://example.com/database-manager-2024",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSswwjJ1rXAwAAiFgK61X4HhE9my3zd7shY6A&s",
  },
  {
    category: "DVDs",
    id: 40,
    name: "Graphics Design Pro",
    description: "Professional tools for graphic design.",
    model: "DVD-GDP",
    brand: "CreateSoft",
    price: 1500,
    salePrice: 699,
    buyLink: "https://example.com/graphics-design-pro",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3ExBG5DUMVrLi5UoWWCIO8f1Q3C2oTt1aEA&s",
  },
];
